### ISSUE TITLE
Jerky movements without colliders

### ISSUE THREAD

**Issue by Barbelot** [brihernandez/MouseFlight#6]
Hello ! 
Thank you for this really nice project, it works really well but I run into a weird behaviour if I disable the colliders on the plane model : the plane movement become very jerky as if he suddenly moved much more sharply.
Reducing the forceMult parameter solves it a bit but also makes it much less responsive.

Any idea why the presence of a collider influence the movement behaviour ? 
Have a nice day !

**Comment by brihernandez** [comment]
This is correct behavior, in the sense that that's how Unity's physics engine (PhysX) works. When there are no colliders on the object, the physics doesn't know how big the object is, so it makes some assumptions. Probably something like "it's a sphere with a diameter of 1 meter" or something like that.

There are two solutions to this.
1. Add an appropriately sized collider(s) to the plane so that it has the necessary physics information 
2. Manually set the [inertiaTensor](https://docs.unity3d.com/ScriptReference/Rigidbody-inertiaTensor.html) on the Rigidbody of the object with values appropriate for your plane. This is automatically calculated when there are colliders on the model, and is a measurement of how hard it is to rotate the model in that axis.

**Comment by Barbelot** [comment]
Oh ok. Thanks for the clarification !
